x-uffizzi:
  ingress:
    service: app
    port: 80
  continuous_previews:
    deploy_preview_when_pull_request_is_opened: true
    delete_preview_when_pull_request_is_closed: false

services:
  app:
    build: .
    deploy:
      resources:
        limits:
          memory: 4000M
    ports:
      - "80:80"
    secrets:
      - admin_secret
      - auto_config
      - frp_token
      - frp_remote_port

secrets:
  admin_secret:
    external: true
    name: "ADMIN_SECRET"
  auto_config:
    external: true
    name: "AUTO_CONFIG"
  frp_token:
    external: true
    name: "FRP_TOKEN"
  frp_remote_port:
    external: true
    name: "FRP_REMOTE_PORT"
